### PR TITLE
add: starfield example in accordance with issue #11

### PR DESCRIPTION
**Pull request by tyagidevansh**
Added a showcase for this game engine, in the sample's folder. The starfield example I added is very similar to the coding train's, however I use polar coordinates to generate the random stars.

This change should not change anything about the project and cause no conflicts. Implementing this example was incredibly simple even though I was previously completely unaware of litecanvas. Great library!

### CODE REVIEW

**Comment by luizbills** [comment]
wow nice job!

Your code is pretty cool, I'll just ask you to make some tweaks:

1. Declare a `update()` function and put all logic there and leave all drawing inside the `draw()` function.
1. Use `rand()` instead of `Math.random()`.
1. Don't edit the `package.json` and `package-lock.json` files (just revert your changes).

**Comment by luizbills** [comment]
Oh! also, would be nice you add your name in a comment, like:
```js
/**
 * @author Devansh Tyagi - https://github.com/tyagidevansh
 */
```

**Comment by tyagidevansh** [comment]
I synced the fork, as my repo was 1 commit ahead and 11 commits behind. I then git pulled, resolved local merge conflicts, and manually copied your original package.json and package-lock.json to make sure they did not have any changes. 
Thank you for your patience, and sorry for the trouble.

**Comment by luizbills** [comment]
> I would be more than happy to close my commit, and delete my fork and start over again.

I also recommend this. Make another pull request by just submitting the starfield fields, without editing the `package.json`. That way it will be fine.

**Pull request closed without merging**
